### ISSUE TITLE
Commands containing unicode

### ISSUE THREAD

**Issue by improbable0101** [andre-d/pympv#6]
Is it possible to send commands containing unicode?

```
>>> import mpv
>>> m = mpv.Context()
>>> m.initialize()
>>> m.command('loadfile', u'a–b.mp3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mpv.pyx", line 560, in mpv.Context.command (mpv.c:8989)
mpv.MPVError: invalid parameter
```

**Comment by andre-d** [comment]
That was supposed to work, I have not looked in this code in a long time
though.  May have only worked in py3

**Comment by tsdko** [comment]
Fixed in marcan@91fe73b6009d8c97757322fa851786a9194c5459, not sure why it hasn't been sent upstream.
